### ISSUE TITLE
Expose function in jswrapper to get address from public key

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/qrllib#150]
Currently there is no way to get a Q address from the public key in the js api wrapper. This is required for ledger integration.

**Comment by jleni** [comment]
It is here:
https://github.com/theQRL/qrllib/blob/fde8eac251c49a23db46a884bdeb7aba5412c1ef/src/jswrapper/jsqrlwrapper.cpp#L227

here is a test:
https://github.com/theQRL/qrllib/blob/fde8eac251c49a23db46a884bdeb7aba5412c1ef/tests/js/test.js#L76
